// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1pqhgc_01PngC4vCNPY3qdfUhnnlHgD8',
    appId: '1:147312761788:web:37f52fe74c37905eb6a9b9',
    messagingSenderId: '147312761788',
    projectId: 'cpd-last-try',
    authDomain: 'cpd-last-try.firebaseapp.com',
    storageBucket: 'cpd-last-try.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZFjeHEv38hesrCkKVf1mSqkwAuEK51q8',
    appId: '1:147312761788:android:3950ef448f778b5fb6a9b9',
    messagingSenderId: '147312761788',
    projectId: 'cpd-last-try',
    storageBucket: 'cpd-last-try.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVN9YBlATpP9hcQv35PSQDPhrsoPIXSxo',
    appId: '1:147312761788:ios:87665bfb5b15982db6a9b9',
    messagingSenderId: '147312761788',
    projectId: 'cpd-last-try',
    storageBucket: 'cpd-last-try.appspot.com',
    iosBundleId: 'com.example.cpdSs23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVN9YBlATpP9hcQv35PSQDPhrsoPIXSxo',
    appId: '1:147312761788:ios:90f906b2aef28b89b6a9b9',
    messagingSenderId: '147312761788',
    projectId: 'cpd-last-try',
    storageBucket: 'cpd-last-try.appspot.com',
    iosBundleId: 'com.example.cpdSs23.RunnerTests',
  );
}
